defaults: &defaults
  custom_field:
    paginates_per: 8
  location:
    paginates_per: 8
  person:
    paginates_per: 8
  search:
    any_p: true
    near_p: true
    results_count_min: 55
    cache_expire_seconds: 3600
    substring_min: 3

development:
  <<: *defaults

test:
  <<: *defaults
  
production:
  <<: *defaults
